### ISSUE TITLE
Clarify language across ui/code/filenames/tutorials/documentation

### ISSUE THREAD

**Issue by delzhand** [delzhand/isocon#325]
terrain/tile/block
token/unit
unitbar/bottombar

**Comment by McPalm** [comment]
I think Block works fine. Terrain doesn't not seem correct due to it reffering to the discrete building part of the terrain.

Unitbar seems better, as its purpose is to store units, and the name would be consistent if it gets moved, or user gets the option to rearrange it.

Token ans Units seem like slightly different concept. The token would be any object on the map representing a unit or object. A unit has a stat sheet attached to it.

The Column class is confusing due to a colomn being a row along the x axis of the board. The class ould perhaps be named Stack/Pillar, perhaps with Block as an affix?

**Comment by delzhand** [comment]
This is probably not a huge problem in itself. Probably room for greater separation between data and presentation in the token/block class but that can be a separate thing if I ever want to address it.
