### ISSUE TITLE
Tokens get in the way when editing the map.

### ISSUE THREAD

**Issue by McPalm** [delzhand/isocon#331]
Its just annoying. The work around is to exit map editing mode, shuffle the tokens around, edit, and then move them back.

https://github.com/delzhand/isocon/assets/22002617/2d0398fe-d39f-4d8a-81d8-e029b6e53c83

**Comment by delzhand** [comment]
What's more, there's some undefined behavior here if another player is moving token while you're editing the map, because map edits aren't real-time. I wonder if we need to lock things down while someone is editing, but even then we've got to account for people who might be dragging tokens or placing terrain markers when someone else enters edit mode.

**Comment by delzhand** [comment]
As long as we teleport tokens to the nearest column first that'll catch anything left stranded by row/column deletes. We'd have to do that to figure out where they are currently anyway, since tokens aren't ever actually "assigned" to a tile, it's always a proximity check.

**Comment by delzhand** [comment]
It might actually be fine to let people move during map editing if they're just going to be teleported to the best match tile afterwards, that would mean we don't have to lock down token movement for the use case of making small tweaks to the map during play. As long as players can see when someone is editing (see #313 ), it should be fine.
